---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
      - 'docs/**'
  push:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
      - 'docs/**'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    strategy:
      matrix:
        name:
          - AC
          - AD
          - ADX
          - AMA
          - ASI
          - ATR
          - ATR_MA_Trend
          - Alligator
          - Awesome
          - BWMFI
          - Bands
          - BearsPower
          - BullsPower
          - CCI
          - Chaikin
          - DEMA
          - DeMarker
          - ElliottWave
          - Envelopes
          - Force
          - Fractals
          - Gator
          - HeikenAshi
          - Ichimoku
          - Indicator
          - MA
          - MA_Breakout
          - MA_Cross_Pivot
          - MA_Cross_Shift
          - MA_Cross_Sup_Res
          - MA_Trend
          - MACD
          - MFI
          - Meta_Bears_Bulls
          - Meta_Double
          - Meta_Mirror
          - Meta_Multi
          - Meta_Oscillator
          - Meta_Reversal
          - Meta_Timezone
          - Meta_Trend
          - Momentum
          - OBV
          - OsMA
          - Oscillator
          - Oscillator_Divergence
          - Oscillator_Multi
          - Oscillator_Cross
          - Oscillator_Cross_Shift
          - Oscillator_Cross_Zero
          - Oscillator_Overlay
          - Oscillator_Range
          - Oscillator_Trend
          - Pattern
          - Pinbar
          - Pivot
          - Retracement
          - RSI
          - RVI
          - SAR
          - SAWA
          - SVE_Bollinger_Bands
          - StdDev
          - Stochastic
          - SuperTrend
          - TMAT_SVEBB
          - TMA_CG
          - TMA_True
          - WPR
          - ZigZag
      max-parallel: 4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          path: Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - uses: actions/checkout@v2
        if: ${{ startsWith(matrix.name, 'Meta_') }}
        with:
          path: Include/EA31337-strategies
          ref: v2.000-dev
          repository: EA31337/EA31337-strategies
          submodules: recursive
      - name: Enables input mode
        run: echo '#define __input__' > ./${{ matrix.name }}/config/define.h
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2361
          path: ./${{ matrix.name }}/Stg_${{ matrix.name }}.mq4
          verbose: true
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: ./${{ matrix.name }}/Stg_${{ matrix.name }}.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
  Compile-All:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          path: Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2361
          path: ./.github/Test.mq4
          verbose: true
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: ./.github/Test.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
